# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NetCDF in Python - from beginner to pro
author: Luke Marsden
logo: logo.png
logo_url: https://www.nordatanet.no/

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: NetCDF_in_Python_from_beginner_to_pro.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/lhmarsden/NetCDF_in_Python_from_beginner_to_pro  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
